name: flutter_split_view
description: Flutter widget that automatically splits the screen into two views based on available space with the ability of making the width adjustable. This is based on Navigator 2.0.
version: 0.2.0
homepage: https://github.com/TerminalStudio/flutter_split_view

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

